# Generated by Django 5.0 on 2023-12-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='videos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
