# Generated by Django 3.2.23 on 2024-02-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
