# Generated by Django 5.0 on 2023-12-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0002_alter_hotel_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='videos',
        ),
    ]
