# Generated by Django 5.0 on 2024-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0003_remove_hotel_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='night_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
