# Generated by Django 5.0.1 on 2024-01-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0004_alter_hotel_night_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='../hotel_photos/'),
        ),
    ]
