# Generated by Django 3.2.23 on 2024-02-02 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0004_booking_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dislikes_count', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.IntegerField(blank=True, default=0, null=True)),
                ('booking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel_your_choice.booking')),
                ('rating', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel_your_choice.rating')),
            ],
        ),
    ]
