# Generated by Django 5.0.1 on 2024-01-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rated_bookings', to='hotel_your_choice.hotel'),
            preserve_default=False,
        ),
    ]
