# Generated by Django 3.2.23 on 2024-02-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rated_bookings',
            field=models.ManyToManyField(blank=True, related_name='rated_hotels', to='hotel_your_choice.Booking'),
        ),
    ]
