# Generated by Django 3.2.23 on 2024-02-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0006_hotel_rated_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hotel_your_choice.hotel'),
        ),
    ]
