# Generated by Django 5.0.1 on 2024-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0007_alter_booking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rated_bookings',
            field=models.ManyToManyField(blank=True, related_name='rated_hotels', to='hotel_your_choice.booking'),
        ),
    ]
