# Generated by Django 5.0.1 on 2024-01-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0008_hotel_rated_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel_your_choice.rating'),
        ),
    ]
