# Generated by Django 5.0.1 on 2024-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0011_alter_hotel_main_photo_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='main_photo',
            field=models.ImageField(upload_to='hotel_main_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='hotel_photos/'),
        ),
    ]
