# Generated by Django 5.0.1 on 2024-01-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0014_alter_hotel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'booking')},
        ),
    ]
