# Generated by Django 5.0.1 on 2024-01-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0015_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
