# Generated by Django 5.0.1 on 2024-01-23 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0017_alter_hotel_main_photo_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='main_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
