# Generated by Django 4.2.7 on 2023-12-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0003_alter_booking_hotel'),
    ]

    operations = [
    ]
