# Generated by Django 4.2.7 on 2023-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0005_auto_20231202_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hotel_manager',
            field=models.BooleanField(default=False),
        ),
    ]
