# Generated by Django 4.2.7 on 2023-12-02 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0006_customuser_is_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_hotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
