# Generated by Django 4.2.7 on 2023-12-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_your_choice', '0008_auto_20231202_1500'),
    ]

    operations = [
    ]
